Script started on 2016年03月06日 (週日) 22時43分08秒
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ exit[K[K[K[Kwhom[Kami ; pwd
H34016128
/home/H34016128
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ git config -;[Kl
user.name=jimmy
user.email=jimmy@yahoo.com.tw
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ git co[Ko[Klone https://github.com/kijy5428/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ ls
[0m[01;34mlab1[0m  lab1.script  [01;34mlab2[0m  typescript
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ rm -rf lab1
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ rm -rf lab1[K[K[K[K[K[K[K[K[K[K[Kls
lab1.script  [0m[01;34mlab2[0m  typescript
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ ls[K[Ktttttttttttttttttttttttttttttttt[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Krm -rf lab1ls[Kgit clone https://github.com/kijy5428/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Compressing objects:  50% (1/2)   [Kremote: Compressing objects: 100% (2/2)   [Kremote: Compressing objects: 100% (2/2), done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;H34016128@2015cpp: ~[01;32mH34016128@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月06日 (週日)  22時49分57秒
